# Generated by Django 3.0.6 on 2020-05-09 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
