# Generated by Django 3.0.6 on 2020-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0002_auto_20200509_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
