# Generated by Django 3.0.6 on 2020-05-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Queue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.BooleanField(default=False)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Queue.Queue')),
            ],
        ),
    ]
