# Generated by Django 3.0.6 on 2020-05-09 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='create_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
