# Generated by Django 3.0.6 on 2020-05-10 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_member_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='session',
            field=models.UUIDField(default=uuid.UUID('9183338d-651e-473a-a174-a25db3566ef0')),
        ),
    ]
