# Generated by Django 3.0.6 on 2020-05-10 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_member_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='session',
            field=models.UUIDField(default=uuid.UUID('63034d28-44cd-4e19-909e-f8b607da84e6'), unique=True),
        ),
    ]
