# Generated by Django 3.0.6 on 2020-05-10 03:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_auto_20200509_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='session',
            field=models.UUIDField(default=uuid.UUID('9a17a936-5d9a-4bfc-9290-1be7e9a2a398'), unique=True),
        ),
    ]
