# Generated by Django 3.0.6 on 2020-05-10 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_auto_20200510_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='session',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
