# Generated by Django 3.0.6 on 2020-05-11 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_auto_20200510_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
